# -----------------------------
# Nightshift Lobo - Kitty (Obsidian)
# -----------------------------

# Core UI
background            #141821
foreground            #D9DEEA
selection_background  #2F3850
selection_foreground  #D9DEEA

cursor                #92A9FF
cursor_text_color     #141821
url_color             #748EF2

active_border_color   #5F77D1
inactive_border_color #353C50
bell_border_color     #DCBE7C

# Tab bar
tab_bar_margin_color    #141821
tab_bar_background      #141821
active_tab_background   #62AEBE
active_tab_foreground   #141821
inactive_tab_background #141821
inactive_tab_foreground #A8AFC8

# -----------------------------
# 16 Color Terminal Palette
# -----------------------------

# Normal colors
color0  #1B202B
color1  #DE8A90
color2  #74C99B
color3  #DCBE7C
color4  #748EF2
color5  #B297F0
color6  #5DB8CB
color7  #A8AFC8

# Bright colors
color8  #2A3142
color9  #EA9AA0
color10 #86D5AB
color11 #E8CB91
color12 #92A9FF
color13 #BFA5FA
color14 #6BC5D8
color15 #D9DEEA

# Extended accents
color16 #D49776
color17 #5F77D1

background_opacity 1.0
