# -----------------------------
# Nightshift Lobo - Kitty (Shadow)
# -----------------------------

# Core UI
background            #10131A
foreground            #D6DBE8
selection_background  #2A344A
selection_foreground  #D6DBE8

cursor                #88A0FF
cursor_text_color     #10131A
url_color             #6F88E6

active_border_color   #6078D4
inactive_border_color #2E3445
bell_border_color     #D8BB78

# Tab bar
tab_bar_margin_color    #10131A
tab_bar_background      #10131A
active_tab_background   #60A9B8
active_tab_foreground   #10131A
inactive_tab_background #10131A
inactive_tab_foreground #A4ABC2

# -----------------------------
# 16 Color Terminal Palette
# -----------------------------

# Normal colors
color0  #181C24
color1  #DA848A
color2  #70C693
color3  #D8BB78
color4  #6F88E6
color5  #AF92EE
color6  #5BB5C8
color7  #A4ABC2

# Bright colors
color8  #242B3A
color9  #E69499
color10 #82D2A3
color11 #E4C88D
color12 #88A0FF
color13 #BCA0F8
color14 #69C2D4
color15 #D6DBE8

# Extended accents
color16 #CF9272
color17 #6078D4

background_opacity 1.0
