# -----------------------------
# Nightshift Lobo - Kitty (Shadow)
# -----------------------------

# Core UI
background            #10131A
foreground            #D6DBE8
selection_background  #2A344A
selection_foreground  #D6DBE8

cursor                #88A0FF
cursor_text_color     #10131A

active_border_color   #88A0FF
inactive_border_color #2E3445

# Tab bar
tab_bar_background      #181C24
active_tab_background   #242B3A
active_tab_foreground   #D6DBE8
inactive_tab_background #181C24
inactive_tab_foreground #687188

# -----------------------------
# 16 Color Terminal Palette
# -----------------------------

# Normal colors
color0  #10131A
color1  #DA848A
color2  #70C693
color3  #D8BB78
color4  #6F88E6
color5  #AF92EE
color6  #5BB5C8
color7  #687188

# Bright colors
color8  #242B3A
color9  #E69499
color10 #82D2A3
color11 #E4C88D
color12 #88A0FF
color13 #BCA0F8
color14 #69C2D4
color15 #D6DBE8

# Optional
background_opacity 1.0
